services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/learn-sams-surfcamp:cached
      - dev-container-node_modules:/workspaces/learn-sams-surfcamp/node_modules
    command: sleep infinity
    env_file:
      - path: ./.cms.env
        required: true
  frontend:
    build:
      context: ../
      dockerfile: ./apps/frontend/Dockerfile
    depends_on:
      - cms
    restart: always
    volumes:
      - ../:/app
      - frontend-node_modules:/app/node_modules
    ports:
      - '3030:3000'
    env_file:
      - path: ./.frontend.env
        required: true
  web:
    build:
      context: ../
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - cms
    restart: always
    volumes:
      - ../:/app
      - web-node_modules:/app/node_modules
    ports:
      - '3040:3000'
  cms:
    build:
      context: ../
      dockerfile: ./apps/cms/Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - ../:/app
      - cms-node_modules:/app/node_modules
    ports:
      - '1337:1337'
    env_file:
      - path: ./.cms.env
        required: true
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  dev-container-node_modules:
  cms-node_modules:
  frontend-node_modules:
  web-node_modules:
  postgres-data:
