services:
  dev-container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces/learn-sams-surfcamp:cached
    command: sleep infinity
  frontend:
    build:
      context: ../
      dockerfile: ./apps/frontend/Dockerfile
    depends_on:
      - cms
    restart: always
    volumes:
      - ../:/app
      - frontend-node_modules:/app/node_modules
    ports:
      - '3030:3000'
  cms:
    build:
      context: ../
      dockerfile: ./apps/cms/Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - ../:/app
      - cms-node_modules:/app/node_modules
    ports:
      - '1337:1337'
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  cms-node_modules:
  frontend-node_modules:
  postgres-data:
